version: '3.1'
networks:
  web:
    external: true
services:
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    networks:
      - web
    ports:
      - 27017:27017
    volumes:
      - /data/mongo-db:/data/db